server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/empdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.empmgmt.domain
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: bXlTdXBlclNlY3JldEtleUZvckp3dFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTAhQCMkJV4mKigp
  expiration: 86400000
